export const GET_PRODUCTS_REQUEST = "GET/PRODUCTS/REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET/PRODUCTS/SUCCESS";
export const GET_PRODUCTS_ERROR = "GET/PRODUCTS/ERROR";




export const LoginSuccess = "LoginSuccess"

export const GET_TOTAL_PRODUCTS_REQUEST = "GET/TOTAL/PRODUCTS/REQUEST";
export const GET_TOTAL_PRODUCTS_SUCCESS = "GET/TOTAL/PRODUCTS/SUCCESS";
export const GET_TOTAL_PRODUCTS_ERROR = "GET/TOTAL/PRODUCTS/ERROR";

export const POST_ADDTOCART_REQUEST = "GET/ADDTOCART/REQUEST";
export const POST_ADDTOCART_SUCCESS = "GET/ADDTOCART/SUCCESS";
export const POST_ADDTOCART_ERROR = "GET/ADDTOCART/ERROR";

export const POST_WISHLIST_REQUEST = "GET/WISHLIST/REQUEST";
export const POST_WISHLIST_SUCCESS = "GET/WISHLIST/SUCCESS";
export const POST_WISHLIST_ERROR = "GET/WISHLIST/ERROR";

